development:
  adapter: postgresql
  encoding: unicode
  database: katuma_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: katuma_test
  pool: 5
  username: postgres
  password:
